const MUSTERLOESUNGEN = {
  1: [
    "Liebe/r [Name],\n\nwie geht es dir? Stell dir vor, ich war letztes Wochenende auf dem Konzert meiner Lieblingsband und es war unfassbar toll! Die Stimmung war gigantisch und alle haben getanzt. Am besten hat mir der Moment gefallen, als sie ihr bekanntestes Lied gespielt haben, weil das ganze Publikum laut mitgesungen hat – das war Gänsehaut pur! Wirklich schade, dass du nicht dabei warst. Hast du vielleicht Lust, nächstes Wochenende gemeinsam einen Kaffee trinken zu gehen? Dann kann ich dir noch mehr erzählen.\n\nMelde dich bald!\nViele Grüße,\n[Dein Name]",
    "Ich möchte mich auch gerne zu diesem Thema äußern, weil es uns alle betrifft. Generell finde ich es super, durch Instagram und WhatsApp mit Freunden auf der ganzen Welt Kontakt zu halten. Aber ich stimme der Meinung vollkommen zu: Oft schauen wir nur noch aufs Display und ignorieren die Personen, die direkt neben uns sitzen. Meiner Meinung nach sollten wir, wenn wir uns mit Freunden treffen, das Handy bewusst weglegen. Nichts kann ein echtes Gespräch und gemeinsames Lachen ersetzen.",
    "Sehr geehrte/r Kursleiter/in,\n\nich melde mich bei Ihnen bezüglich des Musikworkshops nächste Woche. Leider muss ich Ihnen mitteilen, dass ich an diesem Datum nicht teilnehmen kann. Der Grund dafür ist ein dringender Arzttermin, den ich bedauerlicherweise auf keinen Fall verschieben kann. Es tut mir sehr leid. Wäre es eventuell möglich, den Workshop an einem späteren Ersatztermin nachzuholen?\n\nIch danke Ihnen für Ihr Verständnis und freue mich auf Ihre Rückmeldung.\nMit freundlichen Grüßen\n[Ihr Name]"
  ],
  2: [
    "Liebe/r [Name],\n\nich bin endlich wieder zurück aus Rom! Die Städtereise war ein absoluter Traum. Ich habe unzählige Sehenswürdigkeiten besichtigt und jeden Tag unglaublich leckere Pizza und Pasta gegessen. Am besten hat mir der Besuch im Kolosseum gefallen, weil die Geschichte dort einfach greifbar ist und das Gebäude so beeindruckend riesig wirkt. Ich dachte sofort an dich! Hättest du nicht Lust, dass wir nächstes Jahr im Sommer zusammen für ein paar Tage ans Meer fliegen?\n\nLiebe Grüße,\n[Dein Name]",
    "Ich habe die Diskussion gelesen und möchte auch meine Meinung dazu sagen. Es stimmt zwar, dass man viel lernt, wenn man ganz alleine in ein fremdes Land reist. Man wird selbstständiger und lernt, Probleme selbst zu lösen. Trotzdem finde ich, dass das für Jugendliche unter 18 Jahren zu gefährlich sein kann. Außerdem macht das Reisen meiner Meinung nach viel mehr Spaß, wenn man die tollen Erlebnisse und Eindrücke mit Freunden oder der Familie teilen kann.",
    "Sehr geehrte Damen und Herren,\n\nich habe bei Ihnen für kommenden Monat Zimmer für unsere Gruppenreise (Sportverein) gebucht (Buchungsnummer: 12345). Leider hat sich bei uns kurzfristig eine kleine Änderung ergeben. Zwei unserer Mitglieder sind leider krank geworden und können nicht mitfahren. Daher möchte ich Sie höflich bitten, die Buchung von 12 auf 10 Personen abzuändern. Ich hoffe, das ist so kurzfristig noch möglich.\n\nVielen Dank im Voraus für Ihre Mühe.\nMit freundlichen Grüßen\n[Ihr Name]"
  ],
  3: [
    "Liebe/r [Name],\n\nich muss dir unbedingt erzählen, was am Wochenende passiert ist: Ich habe meinen ersten Halbmarathon geschafft! Es war extrem anstrengend, besonders auf den letzten drei Kilometern, aber das Gefühl im Ziel war einfach fantastisch. Ich mache so gerne Sport, weil es mein bester Ausgleich zur Arbeit ist und ich mich danach immer so gesund und energiegeladen fühle. Wenn du möchtest, kann ich dir gerne Tipps für den Anfang geben. Wie wäre es, wenn wir am Sonntag mal zusammen eine kleine, entspannte Runde joggen gehen?\n\nLiebe Grüße,\n[Dein Name]",
    "Das Thema Gesundheit bei Jugendlichen ist momentan sehr aktuell. Ich stimme der Meinung zu, dass viele Jugendliche heutzutage viel zu viel Zeit sitzend vor den Bildschirmen verbringen. Das ist auf Dauer sehr schädlich für den Körper. Aber ich finde nicht, dass nur die Schulen durch mehr Sportunterricht die Lösung sind. Meiner Meinung nach sind auch die Eltern gefragt. Familien sollten am Wochenende öfter gemeinsam aktiv sein, zum Beispiel beim Radfahren oder Wandern in der Natur.",
    "Sehr geehrte Damen und Herren,\n\nvor etwa zehn Tagen habe ich Ihnen über Ihre Website eine Anfrage geschickt, um Mitglied in Ihrem Fitnessstudio zu werden. Bis heute habe ich leider noch keine Rückmeldung von Ihnen erhalten. Da ich wirklich sehr motiviert bin und gerne so schnell wie möglich mit dem Training beginnen möchte, wollte ich noch einmal nachfragen. Könnten Sie mir bitte Informationsmaterial zu den Preisen und Mitgliedschaftsoptionen zusenden?\n\nVielen Dank und herzliche Grüße\n[Ihr Name]"
  ],
  4: [
    "Liebe/r Opa/Oma,\n\nich hoffe, es geht dir gut! Ich wollte dir unbedingt von meinem neuen Smartphone erzählen. Das Highlight ist die großartige Kamera, die bei Nacht unglaublich scharfe Fotos macht. Für mich ist das Gerät im Alltag extrem nützlich, weil ich nicht nur navigieren und chatten kann, sondern auch alle meine Termine für die Uni manage. Du interessierst dich doch so für Pflanzen – es gibt tolle Apps, mit denen man unbekannte Blumen fotografieren und sofort erkennen kann. Soll ich bei meinem nächsten Besuch mal so eine App auf deinem Handy installieren?\n\nLiebe Grüße,\n[Dein Name]",
    "Ich verfolge dieses Thema schon länger und möchte meine Meinung dazu äußern. Ein striktes Verbot von Smartphones für Kinder unter 12 Jahren finde ich etwas extrem. Auf der einen Seite bergen soziale Netzwerke natürlich Gefahren und die Kinder können leicht abgelenkt werden. Auf der anderen Seite wachsen wir heute in einer komplett digitalen Welt auf. Meiner Meinung nach ist es viel sinnvoller, wenn Eltern gemeinsam mit den Kindern lernen, das Smartphone als nützliches Werkzeug zu nutzen, anstatt es einfach nur zu verbieten.",
    "Sehr geehrte Damen und Herren,\n\nich wende mich an Sie bezüglich meiner Online-Bestellung vom 10. Mai (Bestellnummer: 987654). Laut Ihrer Website beträgt die Lieferzeit für das Computerspiel normalerweise 2 bis 3 Werktage. Nun ist jedoch bereits mehr als eine volle Woche vergangen und das Paket ist immer noch nicht bei mir eingetroffen. Ich bitte Sie höflichst, den Status meiner Lieferung zu überprüfen und mir eine kurze Rückmeldung zu geben, wann ich mit dem Paket rechnen darf.\n\nMit freundlichen Grüßen\n[Ihr Name]"
  ],
  5: [
    "Liebe/r [Name],\n\nich hoffe, bei dir ist alles in Ordnung! Ich muss dir von dem Klimamarsch erzählen, bei dem ich gestern in unserer Stadt mitgemacht habe. Die Atmosphäre war einfach unglaublich – tausende Menschen haben friedlich gemeinsam für eine bessere Zukunft demonstriert. Das Thema Klimaschutz liegt mir extrem am Herzen, weil wir nur diese eine Erde haben und die extreme Hitze im Sommer zeigt, dass sich etwas verändern muss. Man kann auch im Alltag richtig viel tun! Wie wäre es, wenn du versuchst, für kurze Strecken komplett auf das Auto zu verzichten und stattdessen das Fahrrad nimmst?\n\nViele Grüße,\n[Dein Name]",
    "Ich finde den Diskussionsbeitrag sehr inspirierend, aber ich muss auch etwas Kritik anbringen. Es ist natürlich fantastisch und extrem umweltfreundlich, nur noch Second-Hand-Mode zu kaufen. Das schont Ressourcen immens. Aber man darf nicht vergessen, dass Second-Hand-Läden nicht für jede Kleidergröße oder jeden persönlichen Geschmack genug Auswahl bieten. Meiner Meinung nach wäre es schon ein großer Schritt in die richtige Richtung, wenn wir alle einfach deutlich weniger neue Kleidung kaufen und unsere Sachen viel länger tragen würden.",
    "Sehr geehrte/r Frau/Herr [Name der Lehrperson],\n\nmit großem Interesse habe ich von dem neuen Umweltprojekt an unserer Schule gehört. Ich würde mich sehr gerne aktiv daran beteiligen. Leider haben Sie mir auf meine letzte E-Mail dazu noch nicht geantwortet, weshalb ich kurz nachfragen wollte. Haben Sie schon Informationen darüber, welche genauen Aufgaben geplant sind und wann das erste gemeinsame Treffen der Gruppe stattfinden wird? Ich bin sehr motiviert und würde mich über eine kurze Rückmeldung freuen.\n\nViele Grüße\n[Ihr Name]"
  ],
  6: [
    "Hallo [Name],\n\nes war so schön, von dir zu lesen! Mir geht es im Moment großartig, denn ich habe letzte Woche mein Abschlusszeugnis bekommen. Die Prüfungsphase davor war allerdings extrem stressig, ich habe wochenlang fast nur in der Bibliothek gesessen. Die harte Arbeit hat sich aber gelohnt, besonders in Biologie. Das Fach mochte ich am meisten, weil wir tolle Experimente gemacht haben und die Themen so nah am echten Leben sind. Hast du nächste Woche Zeit? Wir könnten meinen Abschluss zusammen in unserem alten Lieblingscafé feiern!\n\nLiebe Grüße,\n[Dein Name]",
    "Ich bin beim Lesen dieses Beitrags wirklich hin- und hergerissen. Einerseits wäre es natürlich traumhaft, nach der Schule sofort Freizeit zu haben, ohne noch an Mathematik oder Deutsch denken zu müssen. Andererseits glaube ich, dass Hausaufgaben extrem wichtig sind. Im Unterricht wird oft nur der Stoff erklärt, aber erst, wenn man abends alleine die Aufgaben löst, merkt man, ob man das Thema wirklich verstanden hat. Vielleicht sollte nicht die Hausaufgabe an sich abgeschafft werden, sondern nur die Menge reduziert werden.",
    "Sehr geehrte/r Herr/Frau [Schulleiter/in],\n\nich schreibe Ihnen heute, da ich mich sehr für das angekündigte Austauschprogramm nach Frankreich bewerben möchte. Um meine Bewerbungsunterlagen zu vervollständigen, verlangt die dortige Organisation eine offizielle Bestätigung meiner aktuellen Schule über meinen Status als Schüler/in sowie meine Notenübersicht. Wäre es Ihnen möglich, mir ein solches Dokument in den nächsten Tagen auszustellen? Ich danke Ihnen vielmals im Voraus für Ihre Unterstützung.\n\nMit freundlichen Grüßen\n[Ihr Name]"
  ],
  7: [
    "Liebe/r [Cousin/Cousine],\n\nna, alles gut bei dir? Ich bin gerade super glücklich, denn ich habe endlich meinen ersten Aquarell-Malkurs beendet. Im Kurs haben wir gelernt, wie man Farben richtig mischt und Landschaften malt. Das Highlight war mein eigenes fertiges Bild! Kunst ist für mich total wichtig geworden. Es hilft mir, nach der Arbeit den Kopf freizubekommen und Stress abzubauen. Da du doch auch so gerne kreativ bist: Was hältst du davon, wenn wir nächsten Samstag zusammen in den Park gehen und einfach drauflos zeichnen?\n\nLiebe Grüße,\n[Dein Name]",
    "Ich kann diese sehr extreme Meinung absolut nicht teilen. Unser Gehirn braucht Abwechslung. Wenn wir in der Schule acht Stunden lang nur Mathematik, Biologie oder Physik pauken würden, wären die Schüler völlig überarbeitet. Musik- und Kunstunterricht fördern die Kreativität und zeigen uns, wie man Probleme auf unkonventionelle Weise löst. Solche weichen' Fähigkeiten – das sogenannte kreative Denken – werden auch von modernen Arbeitgebern im späteren Berufsleben extrem stark nachgefragt und geschätzt.",
    "Sehr geehrte Damen und Herren,\n\nam vergangenen Montag habe ich für diesen kommenden Freitagabend online zwei Tickets für das Theaterstück Romeo und Julia gebucht (Buchungscode: TH-987). Zu meinem großen Bedauern bin ich heute stark erkrankt, sodass es mir gesundheitlich absolut unmöglich ist, die Vorstellung zu besuchen. Ich möchte Sie höflich fragen, ob es die Möglichkeit gibt, die Tickets in einen Gutschein umzuwandeln oder auf ein Datum im nächsten Monat umzubuchen?\n\nVielen Dank für Ihre Hilfe.\nMit freundlichen Grüßen\n[Ihr Name]"
  ],
  8: [
    "Liebe/r [Onkel/Tante],\n\ndu wirst es kaum glauben, aber ich koche jetzt regelmäßig selbst! Gestern Abend habe ich ein Rezept für eine asiatische Gemüsepfanne mit Tofu ausprobiert. Das Schneiden hat zwar ewig gedauert, aber geschmacklich war es ein riesiger Erfolg. Mir ist gesunde Ernährung inzwischen extrem wichtig, weil ich gemerkt habe, dass ich tagsüber viel mehr Energie habe und nachts besser schlafe. Da du ja immer so tolle Rezepte kennst: Hättest du am Wochenende vielleicht Zeit, dass wir mal zusammen etwas Neues kochen?\n\nLiebe Grüße,\n[Dein Name]",
    "Das Thema Ernährung weckt immer sehr starke Gefühle. Ich finde vegane Ernährung aus Sicht des Tierschutzes und der Umwelt absolut fantastisch und habe großen Respekt vor Leuten, die das durchziehen. Aber ich lehne extreme Forderungen ab. Man kann nicht von jedem Menschen erwarten, sofort seine kompletten Lebensgewohnheiten radikal zu ändern. Meiner Meinung nach wäre der Gesellschaft schon extrem geholfen, wenn die Mehrheit einfach ihren Fleischkonsum stark reduzieren und bewusster einkaufen würde.",
    "Sehr geehrte Damen und Herren,\n\nich habe mit großem Interesse auf Ihrer Internetseite gelesen, dass Sie im September einen speziellen Kochkurs für italienische Pasta anbieten. Leider musste ich feststellen, dass der Kurs im System bereits als ausgebucht markiert ist. Da ich wirklich sehr, sehr gerne an genau diesem Kurs teilnehmen würde, möchte ich Sie fragen, ob Sie mich auf die Warteliste setzen können? Sobald ein Platz durch eine Absage frei wird, würde ich sofort verbindlich zusagen.\n\nVielen Dank und herzliche Grüße\n[Ihr Name]"
  ],
  9: [
    "Hi [Name],\n\nwie läuft's? Ich muss dir sofort von meinem Praktikum in der Marketing-Agentur erzählen, das ich gestern beendet habe. Ich durfte bei echten Werbekampagnen mithelfen und habe sogar eigene Texte für Social Media verfasst. Die wichtigste Erfahrung für mich war zu sehen, wie ein professionelles Team im Büro zusammenarbeitet – das lernt man einfach nicht in der Schule! Da du bald dein eigenes Praktikum beginnst, rate ich dir: Informiere dich vorher ganz genau über die Firma auf deren Website und stelle immer Fragen, wenn du etwas nicht verstehst.\n\nViel Erfolg und liebe Grüße,\n[Dein Name]",
    "Diesem strengen Kommentar muss ich leider deutlich widersprechen. Nach zwölf Jahren non-stop Schulbankdrücken sind viele Jugendliche einfach erschöpft oder haben überhaupt noch keine Ahnung, was sie die nächsten 40 Jahre beruflich machen wollen. Ein Gap Year, in dem man vielleicht im Ausland arbeitet oder Praktika macht, bringt unfassbar viel wertvolle Lebenserfahrung. Meiner Meinung nach profitieren Arbeitgeber und Universitäten später sehr von jungen Erwachsenen, die selbstständig geworden sind und ihren Horizont erweitert haben.",
    "Sehr geehrte Damen und Herren der Personalabteilung,\n\nam 15. des vergangenen Monats habe ich Ihnen meine vollständigen Bewerbungsunterlagen für den Ausbildungsplatz als Industriekaufmann zugesendet. Da ich bisher noch keine Rückmeldung von Ihnen bekommen habe, möchte ich hiermit höflich nach dem aktuellen Stand meiner Bewerbung fragen. Ich interessiere mich nach wie vor extrem für diese Ausbildungsposition in Ihrem Unternehmen und würde mich über eine Einladung zu einem persönlichen Gespräch sehr freuen.\n\nMit freundlichen Grüßen\n[Ihr Name]"
  ],
  10: [
    "Hallo [Geschwistername],\n\nich melde mich endlich aus meiner neuen WG! Es war wirklich viel Arbeit, aber jetzt bin ich komplett eingerichtet. Die Wohnung ist schön hell und ich teile sie mir mit zwei super netten Studenten. Wir haben sogar einen Balkon! Am meisten schätze ich an der WG, dass ich abends nach der Vorlesung nicht alleine bin und wir oft spontan zusammen kochen oder quatschen können. Das ist viel schöner als eine Einzelwohnung. Hast du Lust, mich nächstes Wochenende zu besuchen? Dann zeige ich dir alles!\n\nLiebe Grüße, \n[Dein Name]",
    "Ich kann den Frust des Schreibers über die hohen Mieten in den Großstädten extrem gut verstehen. Es ist wirklich traurig und unfair, wenn Auszubildende oder Studenten fast ihr gesamtes kleines Einkommen nur für ein kleines Zimmer ausgeben müssen. So wird das Leben in der Stadt zum reinen Luxus. Ich bin fest der Meinung, dass die Regierung hier eingreifen muss. Der Staat sollte dringend mehr bezahlbare Studentenwohnheime bauen und Gesetze gegen die unkontrollierte Erhöhung von Mieten erlassen.",
    "Sehr geehrte/r Frau/Herr [Name],\n\nich wende mich heute an Sie als meine Vermieterin/mein Vermieter bezüglich meiner Wohnung im 2. Stock. Leider muss ich Ihnen mitteilen, dass die Heizung in meinem Badezimmer und im Wohnzimmer seit drei Tagen komplett kalt bleibt, obwohl ich sie voll aufgedreht habe. Da es draußen langsam richtig kalt wird, möchte ich Sie höflich, aber dringend bitten, schnellstmöglich einen Handwerker mit der Reparatur zu beauftragen. Wann könnte dieser vorbeikommen?\n\nVielen Dank für Ihre zeitnahe Hilfe.\nMit freundlichen Grüßen\n[Ihr Name]"
  ]
};
